# __Introduction to NumPy__
#### __1D Array__: Single row of elements like a list. <table> <tr> <td>1</td> <td>2</td> <td>3</td> <td>4</td>   <td>5</td> </tr> </table>
#### __2D Array__: Rows and columns creating a table-like structure.
<table>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>3</td>
  </tr>
  <tr>
    <td>4</td>
    <td>5</td>
    <td>6</td>
  </tr>
  <tr>
    <td>7</td>
    <td>8</td>
    <td>9</td>
  </tr>
</table>

#### __3D Array__: Stack of 2D arrays, adding complexity.
<table>
<tr>
    <td>
      <table>
        <tr>
          <td>1</td>
          <td>2</td>
          <td>3</td>
        </tr>
        <tr>
          <td>4</td>
          <td>5</td>
          <td>6</td>
        </tr>
      </table>
    </td>
    <td>
      <table>
        <tr>
          <td>7</td>
          <td>8</td>
          <td>9</td>
        </tr>
        <tr>
          <td>10</td>
          <td>11</td>
          <td>12</td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <table>
        <tr>
          <td>13</td>
          <td>14</td>
          <td>15</td>
        </tr>
        <tr>
          <td>16</td>
          <td>17</td>
          <td>18</td>
        </tr>
      </table>
    </td>
    <td>
      <table>
        <tr>
          <td>19</td>
          <td>20</td>
          <td>21</td>
        </tr>
        <tr>
          <td>22</td>
          <td>23</td>
          <td>24</td>
        </tr>
      </table>
    </td>
  </tr>
</table>


#### Python's __NumPy__ module manages and manipulates arrays efficiently.
#### __!pip install numpy__


In [ ]:
#This is and example of ne Dimensional Array
 [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [ ]:
#This is an example of two Dimensional Array
#  [ [1, 2, 3],
#   [4, 5, 6],
#   [7, 8, 9] ]


In [ ]:
#This is an example of two Dimensional Array
#  Week 1:
#   Day 1: 72, 75, 78
#   Day 2: 77, 70, 68

# Week 2:
#   Day 1: 74, 73, 76
#   Day 2: 71, 69, 72

In [ ]:
!pip install numpy


In [ ]:
!pip list


Package                            Version
---------------------------------- -------------------
absl-py                            1.4.0
accelerate                         1.3.0
aiohappyeyeballs                   2.4.6
aiohttp                            3.11.12
aiosignal                          1.3.2
alabaster                          1.0.0
albucore                           0.0.23
albumentations                     2.0.4
ale-py                             0.10.2
altair                             5.5.0
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.6.0
arviz                              0.20.0
astropy                            7.0.1
astropy-iers-data                  0.2025.2.17.0.34.13
astunparse                         1.6.3
atpublic                           4.1.0
attrs                              25.1.0
audioread          

# __Import Numpy as np__
#### Import a module or library first.
#### Assigning an alias to a module saves typing.
#### Example: Importing Numpy with alias np. __import numpy as np__
#### Common practice in Python programming.

In [ ]:
import numpy as np


In [ ]:
array = np.array([1, 2, 3, 4, 5])


In [ ]:
array

array([1, 2, 3, 4, 5])

# __Basic Array Creation in numpy__
#### NumPy has many useful functions.
#### Start with the basic function: __np.array__.
#### The array function creates arrays from lists or tuples.
#### It handles multiple dimensions: 1D, 2D, and 3D.

In [ ]:
# Creating a 1D array
one_d_array = np.array([1, 2, 3, 4, 5])
print(one_d_array)


[1 2 3 4 5]


In [ ]:
# Creating a 2D array
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two_d_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Creating a 3D array
three_d_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(three_d_array)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# __Array dimensions, Shape and Size in Numpy__
#### Use __arrayname.ndim__ to check array dimensions
#### Use __arrayname.shape__ attribute shows the size of each dimension
#### Use __arraynmae.size__ attribute shows the total number of elements

In [ ]:
# Checking the dimension of the 1D array
print(one_d_array.ndim)


1


In [ ]:
# Checking the dimension of the 2D array
print(two_d_array.ndim)


2


In [ ]:
# Checking the dimension of the 3D array
print(three_d_array.ndim)


3


In [ ]:
# Checking the shape of the 1D array
print(one_d_array.shape)

(5,)


In [ ]:
# Checking the shape of the 2D array
print(two_d_array.shape)


(3, 3)


In [ ]:
# Checking the shape of the 3D array
print(three_d_array.shape)

(2, 2, 3)


In [ ]:
# Checking the size of the 1D array
print(one_d_array.size)


5


In [ ]:
# Checking the size of the 2D array
print(two_d_array.size)


9


In [ ]:
# Checking the size of the 3D array
print(three_d_array.size)


12


# __Data Types in Numpy__
#### Data types in Numpy: __int, float, complex, bool, str__
#### Integer array: specify dtype parameter as __int__
#### Float array: specify dtype parameter as __float__
#### Complex array: specify dtype parameter as __complex__
#### Boolean array: specify dtype parameter as __bool__
#### String array: specify dtype parameter as __str__
#### Check data type of array using __arrayname.dtype__ attribute


In [ ]:
# Creating an integer array
int_array = np.array([1, 2, 3, 4, 5], dtype=int)


In [ ]:
# Creating a float array
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=float)


In [ ]:
# Creating a complex number array
complex_array = np.array([1+2j, 3+4j, 5+6j], dtype=complex)


In [ ]:
# Creating a boolean array
bool_array = np.array([True, False, True, False], dtype=bool)

In [ ]:
# Creating a string array
string_array = np.array(['apple', 'banana', 'cherry'], dtype=str)


In [ ]:
# Checking the data type of the integer array
print(int_array.dtype)

# Checking the data type of the float array
print(float_array.dtype)

# Checking the data type of the complex array
print(complex_array.dtype)

# Checking the data type of the boolean array
print(bool_array.dtype)

# Checking the data type of the string array
print(string_array.dtype)



int64
float64
complex128
bool
<U6


# __Pseudo Data Generation in numpy__
#### Tool: random function in NumPy __np.random__ for dummy data
#### 1D array with integers: size set to 5
#### 2D array with integers: size set to (3, 4)
#### 3D array with integers: size set to (2, 3, 4)
#### 4D array with integers: size set to (2, 2, 3, 4)
#### Read dimension right to left
##### Right most shows num of columns
##### Second last from right shows number of rows
##### Rest of them shows different levels of stacks or sub-stacks

In [ ]:
# Creating a 1D array with integers
one_d_array = np.random.randint(0, 10, size=5)
print(f'{one_d_array=}')
print(f'{one_d_array.ndim=}')
print(f'{one_d_array.shape=}')
print(f'{one_d_array.size=}')
print(f'{one_d_array.dtype=}')


one_d_array=array([7, 6, 6, 2, 2])
one_d_array.ndim=1
one_d_array.shape=(5,)
one_d_array.size=5
one_d_array.dtype=dtype('int64')


In [ ]:
# Creating a 2D array with integers
two_d_array = np.random.randint(0, 10, size=(3, 4))
print(f'{two_d_array=}')
print(f'{two_d_array.ndim=}')
print(f'{two_d_array.shape=}')
print(f'{two_d_array.size=}')
print(f'{two_d_array.dtype=}')


two_d_array=array([[7, 6, 2, 8],
       [2, 4, 4, 4],
       [0, 3, 1, 4]])
two_d_array.ndim=2
two_d_array.shape=(3, 4)
two_d_array.size=12
two_d_array.dtype=dtype('int64')


In [ ]:
# Creating a 3D array with integers
three_d_array = np.random.randint(0, 10, size=(2, 3, 4))
print(f'{three_d_array=}')
print(f'{three_d_array.ndim=}')
print(f'{three_d_array.shape=}')
print(f'{three_d_array.size=}')
print(f'{three_d_array.dtype=}')


three_d_array=array([[[5, 7, 6, 9],
        [4, 4, 9, 2],
        [2, 9, 9, 0]],

       [[9, 4, 8, 0],
        [6, 6, 7, 9],
        [5, 0, 5, 4]]])
three_d_array.ndim=3
three_d_array.shape=(2, 3, 4)
three_d_array.size=24
three_d_array.dtype=dtype('int64')


In [ ]:
# Creating a 4D array with integers
four_d_array = np.random.randint(0, 10, size=(2, 2, 3, 4))
print(f'{four_d_array=}')
print(f'{four_d_array.ndim=}')
print(f'{four_d_array.shape=}')
print(f'{four_d_array.size=}')
print(f'{four_d_array.dtype=}')

four_d_array=array([[[[8, 2, 8, 8],
         [6, 7, 4, 8],
         [3, 7, 3, 3]],

        [[3, 7, 9, 3],
         [8, 2, 4, 5],
         [7, 2, 6, 1]]],


       [[[8, 4, 6, 9],
         [2, 2, 6, 1],
         [7, 7, 2, 2]],

        [[4, 3, 0, 8],
         [1, 5, 7, 3],
         [4, 0, 2, 3]]]])
four_d_array.ndim=4
four_d_array.shape=(2, 2, 3, 4)
four_d_array.size=48
four_d_array.dtype=dtype('int64')


In [ ]:
# Creating a 4D array with floats
four_d_float_array = np.random.rand(2, 2, 3, 4)
print(f'{four_d_float_array=}')
print(f'{four_d_float_array.ndim=}')
print(f'{four_d_float_array.shape=}')
print(f'{four_d_float_array.size=}')
print(f'{four_d_float_array.dtype=}')


four_d_float_array=array([[[[0.55876217, 0.40278603, 0.32317932, 0.30148661],
         [0.96377083, 0.57505942, 0.10907513, 0.77875542],
         [0.50794979, 0.03639466, 0.49354758, 0.3453315 ]],

        [[0.45483506, 0.72908859, 0.84336893, 0.86706984],
         [0.40113336, 0.09894863, 0.07683178, 0.63161522],
         [0.68644213, 0.66093573, 0.63536286, 0.83944588]]],


       [[[0.62563266, 0.99525135, 0.91461218, 0.5681885 ],
         [0.24577726, 0.33208893, 0.19923222, 0.08862813],
         [0.39698933, 0.93373057, 0.25727752, 0.18864283]],

        [[0.7084572 , 0.78097499, 0.88681415, 0.86358025],
         [0.24613241, 0.52751698, 0.89046946, 0.60833916],
         [0.92842308, 0.04510659, 0.08798539, 0.30810186]]]])
four_d_float_array.ndim=4
four_d_float_array.shape=(2, 2, 3, 4)
four_d_float_array.size=48
four_d_float_array.dtype=dtype('float64')


In [ ]:
# Creating a boolean array
bool_array = np.random.choice([True, False], size=(3, 4))
print(f'{bool_array=}')
print(f'{bool_array.ndim=}')
print(f'{bool_array.shape=}')
print(f'{bool_array.size=}')
print(f'{bool_array.dtype=}')


bool_array=array([[False,  True,  True,  True],
       [False,  True,  True, False],
       [False, False,  True,  True]])
bool_array.ndim=2
bool_array.shape=(3, 4)
bool_array.size=12
bool_array.dtype=dtype('bool')


In [ ]:
import random
import string

# Creating a random string array
def random_string(length):
    letters = string.ascii_letters
    return ''.join(random.choice(letters) for i in range(length))

# Generating an array of random strings
string_array = np.array([[random_string(5) for _ in range(4)] for _ in range(3)])
print(f'{string_array=}')
print(f'{string_array.ndim=}')
print(f'{string_array.shape=}')
print(f'{string_array.size=}')
print(f'{string_array.dtype=}')


string_array=array([['KOVFk', 'vCPPr', 'PXhkI', 'isnUY'],
       ['VyZgV', 'fWVmQ', 'dTxzj', 'SBYrk'],
       ['ruRYY', 'uQNfZ', 'jihZx', 'TKedl']], dtype='<U5')
string_array.ndim=2
string_array.shape=(3, 4)
string_array.size=12
string_array.dtype=dtype('<U5')


# __Explanation of examples created in previous video__
#### Use __choice__ method to pick random values.
#### Create a matrix with True and False values.
#### Example: 2D array with 3 rows, 4 columns.
#### Import __random and string__ modules.
#### __List comprehension__ for concise for loop.
#### Function random_string created by us takes length parameter.
#### __random.choice__ picks letters randomly.
#### Convert list of lists to NumPy array.
#### Check data type, dimensions, shape, and size.
#### __Pythonic way: combine steps with list comprehension.__

In [ ]:
# Creating a boolean array
bool_array = np.random.choice([True, False], size=(3, 4))
print(f'{bool_array=}')
print(f'{bool_array.ndim=}')
print(f'{bool_array.shape=}')
print(f'{bool_array.size=}')
print(f'{bool_array.dtype=}')

bool_array=array([[ True,  True,  True, False],
       [ True, False, False, False],
       [ True, False, False,  True]])
bool_array.ndim=2
bool_array.shape=(3, 4)
bool_array.size=12
bool_array.dtype=dtype('bool')


In [ ]:


# Creating a 3x4 array with animal names
animal_array = np.random.choice(['dog', 'cat', 'lion', 'cow', 'goat'], size=(3, 4))
print(animal_array)
print(animal_array.ndim)
print(animal_array.shape)
print(animal_array.size)
print(animal_array.dtype)


[['lion' 'goat' 'goat' 'cow']
 ['cat' 'cat' 'lion' 'dog']
 ['dog' 'dog' 'goat' 'cat']]
2
(3, 4)
12
<U4


In [ ]:
# Example of list comprehension to create a list of the first 10 digits
ten_digits = [x for x in range(10)]
print(ten_digits)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# Example of list comprehension to create a list of squares of numbers from 0 to 9
squares = [x**2 for x in range(10)]
print(squares)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
import random
import string

def random_string(length):
    letters = string.ascii_letters
    print(letters)
    char_list = [random.choice(letters) for i in range(length)]
    print(char_list)
    print(''.join(char_list))
    # return ''.join(random.choice(letters) for i in range(length))

random_string(5)


abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
['O', 'H', 'e', 'v', 'V']
OHevV


In [ ]:
def random_string(length):
    letters = string.ascii_letters
    return ''.join(random.choice(letters) for _ in range(length))

# Example function call
print(random_string(5))

hTqJZ


In [ ]:
# Example function call
print(random_string(9))

tUfdGWuFZ


In [ ]:
rand_st = random_string(9)
print(rand_st)

dYHsgmaWD


In [ ]:
string_array = []
for _ in range(3):
    row = []
    for _ in range(4):
        row.append(random_string(5))
    string_array.append(row)
print(string_array)

[['JdxyL', 'rsRhQ', 'gajPh', 'qcmWO'], ['pwCZC', 'uXBDM', 'JwyoH', 'xAAha'], ['hescR', 'GyXgH', 'qFifo', 'gCViy']]


In [ ]:
type(string_array)

list

In [ ]:
numpy_array = np.array(string_array)
print(numpy_array)

[['JdxyL' 'rsRhQ' 'gajPh' 'qcmWO']
 ['pwCZC' 'uXBDM' 'JwyoH' 'xAAha']
 ['hescR' 'GyXgH' 'qFifo' 'gCViy']]


In [ ]:
type(numpy_array)

numpy.ndarray

In [ ]:
print(numpy_array.ndim)
print(numpy_array.shape)
print(numpy_array.size)

2
(3, 4)
12


In [ ]:
string_array = np.array([[random_string(5) for _ in range(4)] for _ in range(3)])
print(string_array)
print(string_array.ndim)
print(string_array.shape)
print(string_array.size)

[['mtNug' 'GTUkB' 'tplWX' 'PKrrW']
 ['LeqPK' 'GHMdK' 'CUapP' 'fByCB']
 ['IGYEA' 'mZWet' 'MiILE' 'hymQG']]
2
(3, 4)
12


In [ ]:
import random
import string

# Creating a random string array
def random_string(length):
    letters = string.ascii_letters
    return ''.join(random.choice(letters) for i in range(length))

# Generating an array of random strings
string_array = np.array([[random_string(5) for _ in range(4)] for _ in range(3)])
print(f'{string_array=}')
print(f'{string_array.ndim=}')
print(f'{string_array.shape=}')
print(f'{string_array.size=}')
print(f'{string_array.dtype=}')
print(f'{type(string_array)=}')

string_array=array([['wNQCT', 'Scwri', 'lYuXf', 'VTSyW'],
       ['SWzLn', 'BpeOx', 'CphuP', 'KlHFe'],
       ['gwztC', 'WWyxt', 'vDUpo', 'fxnSR']], dtype='<U5')
string_array.ndim=2
string_array.shape=(3, 4)
string_array.size=12
string_array.dtype=dtype('<U5')
type(string_array)=<class 'numpy.ndarray'>


# __Array Indexing and Slicing__
#### Indexing: Access individual elements in arrays or lists.
#### Python arrays (lists) are __zero-indexed__.
#### Use square brackets __[]__ to specify element indices.
#### Slicing: Retrieve subsets of elements from arrays/lists.
#### Syntax for slicing: __my_array[start:end]__.
#### Add step value: __my_array[start:end:step]__ for intervals.
#### Indexing in 2D arrays involves __row, column indices__.
#### Slicing in 2D arrays extracts subarrays with ranges.
#### Example: extract columns in second row with a colon.
#### Understanding indexing/slicing enhances data manipulation.

In [ ]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D Array:", array_1d)
print(f'Data type is {type(array_1d)}')

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
Data type is <class 'numpy.ndarray'>


In [ ]:
# Indexing
print("Element at index 2:", array_1d[2])

Element at index 2: 3


In [ ]:
# Slicing
print("Elements from index 2 to 5:", array_1d[2:6])  # Extracts elements from index 2 to 5
print("Every second element:", array_1d[::2])  # Skips every other element
print("Last element using negative index:", array_1d[-1])  # Accesses the last element

Elements from index 2 to 5: [3 4 5 6]
Every second element: [1 3 5 7 9]
Last element using negative index: 10


In [ ]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Indexing
print("Element at row 1, column 2:", array_2d[1, 2])

Element at row 1, column 2: 6


In [ ]:
# Slicing
print("Second row:", array_2d[1, :])
print("Second column:", array_2d[:, 1])
print("Subarray from row 0 to 1 and column 1 to 2:\n", array_2d[0:2, 1:3])

Second row: [4 5 6]
Second column: [2 5 8]
Subarray from row 0 to 1 and column 1 to 2:
 [[2 3]
 [5 6]]


In [ ]:
# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("3D Array:\n", array_3d)

# Indexing
print("Element at depth 1, row 0, column 1:", array_3d[1, 0, 1])

# Slicing
print("First depth:\n", array_3d[0, :, :])
print("Second column across all depths:\n", array_3d[:, :, 1])
print("Subarray from depth 0 to 1 and row 0 to 1:\n", array_3d[0:2, 0:2, :])


3D Array:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Element at depth 1, row 0, column 1: 6
First depth:
 [[1 2]
 [3 4]]
Second column across all depths:
 [[ 2  4]
 [ 6  8]
 [10 12]]
Subarray from depth 0 to 1 and row 0 to 1:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Creating a 4D array
array_4d = np.random.randint(1, 10, size=(2, 2, 2, 2))
print("4D Array:\n", array_4d)

# Indexing
print("Element at depth 0, height 1, row 0, column 1:", array_4d[0, 1, 0, 1])

# Slicing
print("First depth and height:\n", array_4d[0, 0, :, :])
print("Second row across all depths and heights:\n", array_4d[:, :, 1, :])
print("Subarray from depth 0 to 1, height 0 to 1, and row 0 to 1:\n", array_4d[0:2, 0:2, 0:2, :])


4D Array:
 [[[[7 4]
   [2 1]]

  [[6 5]
   [8 8]]]


 [[[1 5]
   [1 2]]

  [[6 8]
   [3 8]]]]
Element at depth 0, height 1, row 0, column 1: 5
First depth and height:
 [[7 4]
 [2 1]]
Second row across all depths and heights:
 [[[2 1]
  [8 8]]

 [[1 2]
  [3 8]]]
Subarray from depth 0 to 1, height 0 to 1, and row 0 to 1:
 [[[[7 4]
   [2 1]]

  [[6 5]
   [8 8]]]


 [[[1 5]
   [1 2]]

  [[6 8]
   [3 8]]]]


# __Array Shape and Reshape__
#### Understanding array shape aids in data manipulation.
#### Shape of array describes its dimensions (e.g., 2D, 4D).
#### Reshape method changes array shape without altering data.
#### Examples: Changing 1D to 2D, 3D, 4D arrays.

In [ ]:
import numpy as np

# Creating a 1D array with 12 elements
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("1D Array:", array_1d)

# Reshaping the 1D array to a 2D array with 3 rows and 4 columns
array_2d = array_1d.reshape(3, 4)
print("2D Array:\n", array_2d)


1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Reshaping the 1D array to a 3D array with 2 blocks, each containing 3 rows and 2 columns
array_3d = array_1d.reshape(2, 3, 2)
print("3D Array:\n", array_3d)


3D Array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Reshaping the 1D array to a 4D array with 2 blocks, each containing 2 blocks of 3 rows and 1 column
array_4d = array_1d.reshape(2, 2, 3, 1)
print("4D Array:\n", array_4d)


4D Array:
 [[[[ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]]]


 [[[ 7]
   [ 8]
   [ 9]]

  [[10]
   [11]
   [12]]]]


In [ ]:
# Creating a 2D array with 2 rows and 6 columns
array_2d_non_square = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print("Non-Square 2D Array:\n", array_2d_non_square)


Non-Square 2D Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# Reshaping the 2D array to a 1D array
array_1d_from_2d = array_2d_non_square.reshape(-1)
print("1D Array from 2D:\n", array_1d_from_2d)


1D Array from 2D:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Reshaping the 2D array to a 3D array with 2 blocks, each containing 3 rows and 2 columns
array_3d_from_2d = array_2d_non_square.reshape(2, 3, 2)
print("3D Array from 2D:\n", array_3d_from_2d)


3D Array from 2D:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Reshaping the 2D array to a 4D array with 2 blocks, each containing 2 blocks of 3 rows and 1 column
array_4d_from_2d = array_2d_non_square.reshape(2, 2, 3, 1)
print("4D Array from 2D:\n", array_4d_from_2d)


4D Array from 2D:
 [[[[ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]]]


 [[[ 7]
   [ 8]
   [ 9]]

  [[10]
   [11]
   [12]]]]


# __Special dimension in Numpy__
#### __-1__ allows NumPy to auto-calculate dimension size.
#### Ensures total number of elements remains consistent.
#### Example: reshape 2D array (2, 6) to 1D array.
#### Illustrates flexibility and convenience of using -1

In [ ]:
# Creating a non-square shaped 2D array
array_2d_non_square = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print("Non-Square 2D Array:\n", array_2d_non_square)

# Reshaping the 2D array to a 1D array
array_1d_from_2d = array_2d_non_square.reshape(-1)
print("1D Array from 2D:\n", array_1d_from_2d)


Non-Square 2D Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
1D Array from 2D:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Creating a 1D array with 24 elements
array_1d = np.arange(24)
print("1D Array:", array_1d)

# Reshaping the 1D array to a 3D array with dimensions (2, 3, 4)
array_3d = array_1d.reshape(2, 3, 4)
print("3D Array:\n", array_3d)


1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# Reshaping the 3D array to a 2D array with dimensions (4, -1)
array_2d_from_3d = array_3d.reshape(4, -1)
print("2D Array from 3D:\n", array_2d_from_3d)


2D Array from 3D:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
# Creating a 4D array with 2 blocks, each containing 2 blocks of 3 rows and 2 columns
array_4d = np.arange(24).reshape(2, 2, 3, 2)
print("4D Array:\n", array_4d)

# Reshaping the 4D array to a 2D array
array_2d_from_4d = array_4d.reshape(-1, 6)  # Automatically calculates the first dimension
print("2D Array from 4D:\n", array_2d_from_4d)


4D Array:
 [[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]]
2D Array from 4D:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
# Creating a 2D array with 3 rows and 6 columns
array_2d = np.arange(18).reshape(3, 6)
print("2D Array:\n", array_2d)

# Reshaping the 2D array to a 3D array with dimensions (2, -1, 3)
array_3d_from_2d = array_2d.reshape(2, -1, 3)
print("3D Array from 2D:\n", array_3d_from_2d)


2D Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
3D Array from 2D:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


# __Handling Missing Data in Numpy__
#### Missing data in large arrays is managed using __NaN and inf__.
#### __inf__ can be postive or negative
#### Use __isnan__ to identify __NaN__ values in an array.
#### Use __isinf__ to identify __infinite__ values in an array.
#### Replace NaN and inf with specific values using __nan_to_num__.
#### Positive and negative inf can be replaced with different values.
#### Managing missing data ensures reliable, accurate analyses.

In [ ]:
import numpy as np

# Creating an array with NaN and inf values
array = np.array([1, 2, np.nan, 4, np.inf, 6, np.nan, 8, -np.inf])
print("Original Array:", array)


Original Array: [  1.   2.  nan   4.  inf   6.  nan   8. -inf]


In [ ]:
# Identifying NaN values
nan_values = np.isnan(array)
print("NaN Values:", nan_values)


NaN Values: [False False  True False False False  True False False]


In [ ]:
# Identifying infinite values
inf_values = np.isinf(array)
print("Infinite Values:", inf_values)


Infinite Values: [False False False False  True False False False  True]


In [ ]:
# Replacing NaN and inf values with specific numbers
cleaned_array = np.nan_to_num(array, nan=0.0, posinf=1000.0, neginf=-1000.0)
print("Cleaned Array:", cleaned_array)


Cleaned Array: [    1.     2.     0.     4.  1000.     6.     0.     8. -1000.]


# __Numpy performance comparison__
#### Compare performance of Python operations vs. NumPy.
#### Arrays' ease of use boosts Python's popularity in ML.
#### Use __%%time__ in Jupyter/Colab for performance measurement.
#### Sine calculation of 10 million numbers using Python.
#### User time: CPU executing code in user mode.
#### System time: CPU executing system-level operations.
#### Total CPU time: Sum of user and system time.
#### __Wall time__: Real-world elapsed time including delays.
#### NumPy performance is 5-6 times better than Python.
#### __Vector__ is another term we use for arrays.

In [ ]:
%%time

import math

# Create a list of numbers
num_list = [i for i in range(10000000)]

# Calculate the sine of each element using a for loop
exp_list = [math.sin(x) for x in num_list]


CPU times: user 1.17 s, sys: 889 ms, total: 2.06 s
Wall time: 2.1 s


In [ ]:
%%time

import numpy as np

# Create a NumPy array of numbers
num_array = np.arange(10000000)

# Calculate the sine of each element using np.sin
exp_array = np.sin(num_array)


CPU times: user 212 ms, sys: 45.8 ms, total: 258 ms
Wall time: 253 ms


# __Universal Functions in Numpy__
| Function            | Description                                                                                                      |
|---------------------|------------------------------------------------------------------------------------------------------------------|
| abs, fabs           | Compute the absolute value element-wise for integer, floating-point, or complex values                           |
| sqrt                | Compute the square root of each element (equivalent to arr ** 0.5)                                               |
| square              | Compute the square of each element (equivalent to arr ** 2)                                                      |
| exp                 | Compute the exponent of each element                                                                             |
| log, log10, log2, log1p | Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively                           |
| sign                | Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)                                       |
| ceil                | Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)            |
| floor               | Compute the floor of each element (i.e., the largest integer less than or equal to each element)                 |
| rint                | Round elements to the nearest integer, preserving the dtype                                                      |
| modf                | Return fractional and integral parts of array as separate arrays                                                 |
| isnan               | Return boolean array indicating whether each value is NaN (Not a Number)                                         |
| isfinite, isinf     | Return boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively      |
| cos, cosh, sin, sinh, tan, tanh | Regular and hyperbolic trigonometric functions                                                       |
| arccos, arccosh, arcsin, arcsinh, arctan, arctanh | Inverse trigonometric functions                                                   |
| logical_not         | Compute truth value of not x element-wise (equivalent to ~arr)                                                   |
| add                 | Add corresponding elements in arrays                                                                             |
| subtract            | Subtract elements in second array from first array                                                               |
| multiply            | Multiply array elements                                                                                          |
| divide, floor_divide| Divide or floor divide (truncating the remainder)                                                                |
| power               | Raise elements in first array to powers indicated in second array                                                |
| maximum, fmax       | Element-wise maximum; fmax ignores NaN                                                                           |
| minimum, fmin       | Element-wise minimum; fmin ignores NaN                                                                           |
| mod                 | Element-wise modulus (remainder of division)                                                                     |
| copysign            | Copy sign of values in second argument to values in first argument                                               |
| greater, greater_equal, less, less_equal, equal, not_equal | Perform element-wise comparison, yielding boolean array (equivalent to infix operators >, >=, <, <=, ==, !=) |
| logical_and, logical_or, logical_xor | Compute element-wise truth value of logical operation (equivalent to infix operators & |, ^)   |


In [ ]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Use add ufunc to add corresponding elements
result = np.add(array1, array2)
print(result)


[5 7 9]


In [ ]:
import numpy as np

# Create an array
array = np.array([1, 4, 9, 16])

# Use sqrt ufunc to compute the square root of each element
result = np.sqrt(array)
print(result)


[1. 2. 3. 4.]


In [ ]:
import numpy as np

# Generate an array of 1000 random integers between 0 and 100
random_array = np.random.randint(0, 100, size=1000)

# Sort the array using np.sort
sorted_array = np.sort(random_array)

print("Original Array:", random_array)
print("Sorted Array:", sorted_array)


Original Array: [ 5 29 95 25 65 46 88 94 92 76 90 49 87 20 93 34 17 52 90 67 84 62 70 53
 47 19 26 72 40 39 58 47 31 77 21 75 99 21 60 57 94 79 52 60 26 25 25 56
 51 22 19 87 89 20 82 57  7 57 74 74 45 65 30 84 77 62 55 21  6 93 52  3
  9 97 41 47 92 95 19 32 32 62 46 92 98  8 20 70 17 20 69 16 31 23  7 40
 30 89 44 61 19  7 32 65 80 14 52 39 21  4 15  7 56 93 52 79 17 10 23 82
 60 69 43 91 59 49 95  3 14  4 78 44 35 75 16 35 84 46 65 90 26 92 71 53
 50 31 31 77 79 97 31 12  3 45 48 66 46 58 98 67 91 72 29 96 19 36 85 44
 15 58 75 58 50 57 55 38 23 26 71 44 84 74 35 97 48 41 77  9 61 88 39 67
 12 90 36 21 99 87 12 89 48  2 14 96  9 20 40 31 67 30 79 56 43 14 15  7
 52 31 49 30 72 87 22 40 21 11 22 89 42 45 62 63 82 68 99 62 11 82  3 36
 13 48 76  6 17 94 53 76 18 71 82 69 49 15 93 60 59 44 94 16 60 55 38 39
 95 74 10 45 23 47 37 86 74 49 60 71 96 45 50 44 71 68 85 77 58 93 44 32
 45 79 18 13 11  1 45  8 42 67 38 63 18 46 55 33 50  2 89 28 92 12 48 25
 40 76  0 42 34 85  2 18 20 28 23 5

In [ ]:
import numpy as np

# Generate an array of 1000 random integers between 0 and 100
random_array = np.random.randint(0, 100, size=1000)

# Find unique values in the array using np.unique
unique_values = np.unique(random_array)

print("Original Array:", random_array)
print("Unique Values:", unique_values)


Original Array: [82  1 14 48 57 45 31 75 73  1 62 20 73 67 11 46 90 93 27  8 77 27 99  1
 23 47  5 26 50 95 49 86 87  7 31 50 71 13 53 42 59 86 79 30  0 29 98 75
 19 11 20 48 57 66 89 29 90 92 45 99 12 77  9 90 99 80 38 43 98 54 38 43
 58 85 69 58 97 87 88 42 19 78 93 62 89 54 74 57 14 62 16 14 68 46  4 50
 51 49  6 39 52 11  3  6 29 34 97 71 89 95  6 95 83 61 55 49 62 51 62 37
 91 81 21  0 22 54 73 89 52 60 99 94 12 78 29  0 57 74 70 20 53 56 24 55
 15 99 64 68 62  0 13 60 73 65 16 51 51 14 57 52 53 67 90 39 54 62 52 52
 59 36 80 43 45 51 89 73 38 50 74 80 66 42 16 11  9 33 88 56 66 42 41 76
 89  9 53 55 94 51 12  2 71  3  8  6 65 42 44 65  4 55  8 72 85 58 57 63
 97  2 56 97 82 56 42 74 38 66 28  0 92 10 61 78 77 98 95 78 20 33 39 58
 85 91 23 82 75 51 69 97 48 84 87 27 26 11 24 68 48 36 11 23 33 91 23 26
 94 31 77  7  4 95 56 19 34 71 62 66 41 88 74 76 79 82 64 19 28 92 44 86
 72 47 49 79 75 92 81 41 81 41 93 91 96 33 45  5 25 70 44 13 46 33 30 97
 10  6 48 50 79 14 99 54 15 49 50 1

In [ ]:
import numpy as np

# Create a 4D array of shape (2, 3, 4, 5)
array = np.random.randint(0, 100, size=(2, 3, 4, 5))

# Access the element at [1, 2, 3, 4]
element = array[1, 2, 3, 4]

# Slice the array to get a 2D slice at the last two dimensions
slice_2d = array[:, :, 3, 4]



# __Where in Numpy__
#### __np.where()__ enables conditional logic, providing alternatives for both true and false conditions element-wise.
#### It handles floating-point operations seamlessly, such as replacing specific values with NaN.
#### Versatile for transformations, it simplifies tasks like data cleaning and numerical modification efficiently.

In [5]:
# Create data
import numpy as np

arr = np.array([5, 10, 15, 20])
arr

array([ 5, 10, 15, 20])

In [6]:
# Apply np.where() to replace values greater than 10 with 1, otherwise 0
result = np.where(arr > 10, 1, 0)
result


array([0, 0, 1, 1])

In [7]:
# Replace values greater than 10 with NaN
arr_with_nan = np.where(arr > 10, np.nan, arr)
arr_with_nan


array([ 5., 10., nan, nan])